# Generated by Django 4.1.3 on 2023-02-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('menu', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodItems',
            new_name='FoodItem',
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='updated_ad',
            new_name='updated_at',
        ),
    ]
